; Version 1.5

; === Variables ===
[Variables]

; ===== Dimensions =====
CoverSize=200
CoverSizeHalf=(80)
SmallCoverSize=(#CoverSize#/2)
PlayerIconSize=(#SmallCoverSize#/2.5)
CoverOffset=0

; ===== Spacing =====
Padding=20
SmallCoverMargin=20
PlayerIconMargin=10
DecoIconMargin=-50

; ===== Colors =====

; == Dark ==

; Background
BGColor_Dark=27,28,29

; Accents
AccentColor_Dark=241,241,241
TextColor_Dark=241,241,241

; Progress Bar
ProgressBGColor_Dark=48,48,48

; == Light == 

; Background
BGColor_Light=241,241,241

; Accents
AccentColor_Light=21,21,21
TextColor_Light=21,21,21

; Progress Bar
ProgressBGColor_Light=48,48,48,50

; == Multi ==
AccentColor_Red = 215,25,34

; ===== Animation =====
HoverOffset=120
AnimationSpeed=5
AnimationSteps=60
AnimationDuration=50
EasingFactor=0.5
ReturnSpeedMultiplier=2

; ===== Typography =====
FontFace=Roboto
TitleFontSize=14
ArtistFontSize=14
TitleFontWeight=400
ArtistFontWeight=100
CharacterSpacing=1

; ===== Layout =====
; Corners
CornerRadius=27

; Progress Bar
ProgressBarHeight=3
ProgressBarRadius=2

; Positioning
InfoTextYOffset=40
ArtistTextYOffset=70
ProgressBarYOffset=10

; ===== Icons =====
DecoIconSize=25

; ===== Default Images =====
DefaultCover=#@#Images/NothingCover.png
DefaultPlayerIcon=#@#Icons/Spotify.png

; ===== Animation Timings =====
TintDuration=500
FadeSteps=10
FadeInterval=10
IconFadeSteps=10
IconFadeInterval=20

; Equalizer Settings
EqualizerBarWidth=5
EqualizerBarMaxHeight=15
EqualizerBarMinHeight=5
EqualizerBarSpacing=2
EqualizerBarCount=4
EqualizerBottomMargin=25
EqualizerLeftMargin=25
EqualizerSensitivity=2.5
EqualizerSmoothing=0.7


EqualizerCurrentColor=241,241,241,180 ; Default

LightBarColor=241,241,241
DarkBarColor=48,48,48

; === Circle Sizes ===
CircleSize=90

